### ISSUE TITLE
This dont work because grecaptcha not supported in WKWebView.

### ISSUE THREAD

**Issue by andymedvedev** [ThinkChaos/reCaptchaiOS#3]
Hello!
I run project but nothing happens.. after that i discovered that in script in catch statement returns error: "Can't find variable: grecaptcha".

What you think about this?

Thanks in advance!

**Comment by ThinkChaos** [comment]
I believe this is related to the site hosting the CAPTCHA.
Can you link the page with the CAPTCHA so that I take a look?

**Comment by andertsk** [comment]
I discovered that the site must include captcha script to work with your code.

**Comment by andymedvedev** [comment]
looks like that site must have injected reCaptcha script from google.
I've added some tricks in script that you implemented before. https://github.com/andertsk/iOSreCaptcha

**Comment by ThinkChaos** [comment]
The reason I load the webpage and inject my script is for reCaptcha to have a correct Referer HTTP header.
I didn't have control over the site so I couldn't add localhost to the list of allowed domains. Because you do have access, your method also works.
Alternatively you could also inject the reCaptcha `<script>` element in the page to avoid adding localhost to the allowed domains.

I'll close this issue but feel free to comment if you want to add anything!
